### ISSUE TITLE
[Feature Request] Add pretuned text styling

### ISSUE THREAD

**Issue by ryuujo1573** [yxw007/vscode-translate-next#1]
To be specific, it's widely seen as prompt texts for i18n strings to apply translations like:
```diff
- 我们如何称呼您？
+ What's your name?

# with difference casualty
- What's your name?
+ How should we address you?
+ Hey, how should we call you?
```

Please add some selection on translation `casualty`, and, further, `scenarios`.

**Comment by yxw007** [comment]
> To be specific, it's widely seen as prompt texts for i18n strings to apply translations like:
> 
> ```diff
> - 我们如何称呼您？
> + What's your name?
> 
> # with difference casualty
> - What's your name?
> + How should we address you?
> + Hey, how should we call you?
> ```
> 
> Please add some selection on translation `casualty`, and, further, `scenarios`.

Not quite sure what you mean, can you explain in detail with an example?
