### ISSUE TITLE
使用DeepL作为翻译源时，鼠标悬停在任意函数名上出现400报错

### ISSUE THREAD

**Issue by LPHsuzu** [yxw007/vscode-translate-next#10]
![屏幕截图 2024-12-08 162209](https://github.com/user-attachments/assets/19bd1555-fd98-44ae-9ca9-c6f379194c27)
![屏幕截图 2024-12-08 162253](https://github.com/user-attachments/assets/c0cfb859-8260-4d1b-ac62-c30fd1d22c89)
![Uploading 屏幕截图 2024-12-08 162624.png…]()

**Comment by yxw007** [comment]
已解决，用新包试试，如果未解决可重新打开
