### ISSUE TITLE
Engine google not found

### ISSUE THREAD

**Issue by 1765659645** [yxw007/vscode-translate-next#3]
Engine google not found
![image](https://github.com/user-attachments/assets/472bee05-75ba-41da-abe3-f6a99899612d)

**Comment by yxw007** [comment]
> Engine google not found ![image](https://private-user-images.githubusercontent.com/57136514/379679869-472bee05-75ba-41da-abe3-f6a99899612d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9. eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjExMzYsIm5iZiI6MTcyOTc2MDgzNiwicGF0aCI6Ii81 NzEzNjUxNC8zNzk2Nzk4NjktNDcyYmVlMDUtNzViYS00MWRhLWFiZTMtZjZhOTk4OTk2MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFW Q09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA5MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2ln bmF0dXJlPTMzYTZkMGZlMWJhMjBhMTg1Mzg4OTg3MWY2MzA5MjUwODYyMDdmY2U4NDBlYzE1M2MzNTA1ZWI3MGNmZDEwOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TSudEpitDvLSUB MpMoFsR_kgqg3_s2ZfPNbIEpfNQoo)

My local test works fine, try uninstalling and reinstalling

**Comment by 1765659645** [comment]
I have tried uninstalling and reinstalling it several times, and turning on VPN, but it keeps giving me the same error. I'm not sure if it has something to do with the device being a MAC.

**Comment by yxw007** [comment]
> I have tried uninstalling and reinstalling it several times, and turning on VPN, but it keeps giving me the same error. I'm not sure if it has something to do with the device being a MAC.

I have found the problem, and I will tell you after the update;
