### ISSUE TITLE
设置了百度翻译的id 和秘钥还是报错

### ISSUE THREAD

**Issue by YH2021-cc** [yxw007/vscode-translate-next#4]
![image](https://github.com/user-attachments/assets/a37fcd7b-378b-4943-b906-873d16885df8)

![image](https://github.com/user-attachments/assets/c257c81f-cbf1-4848-8954-c3bde044a527)

而且输出栏里没有错误信息

其他设置
![image](https://github.com/user-attachments/assets/efd8475d-e7ee-4291-b962-5100e4f45f79)
![image](https://github.com/user-attachments/assets/493325a0-87d8-4cb0-b82e-fc9089961b15)

**Comment by YH2021-cc** [comment]
百度翻译控制台
![image](https://github.com/user-attachments/assets/09983cd1-5ed8-4678-94ad-9734c7c330dd)

**Comment by yxw007** [comment]
@YH2021-cc 你没有开通翻译服务，需要开通翻译服务就可以了。
![image](https://github.com/user-attachments/assets/680b550a-5d4b-4f69-bf24-6265ef866540)
![image](https://github.com/user-attachments/assets/c1e6bd0b-11da-4865-8875-4cc9b74d74fa)

**Comment by YH2021-cc** [comment]
嗯嗯可以了之前申请的是通用文本翻译

**Comment by yxw007** [comment]
好的，恭喜你成功了 

> 嗯嗯可以了之前申请的是通用文本翻译
