### ISSUE TITLE
百度翻译的api，调用返回52003问题

### ISSUE THREAD

**Issue by LY-zhang-yi-hao** [yxw007/vscode-translate-next#6]
你好，百度翻译的api，是否能够调用成功？我在填写相关信息后，返回了api错误码52003。
具体信息：Translate fail ! error_code:52003, error_msg: UNAUTHORIZED USER
查了下报错是用户未开通此项服务。但是我确实已经开通了，。将api填入到其他翻译插件，发现可以正常返回翻译内容。
![image](https://github.com/user-attachments/assets/886f5644-d115-42c2-add5-8ae95be34ccb)
查了相关教程，您看可能是您那边的调用代码有问题？https://blog.csdn.net/J_aSON_/article/details/114798090

**Comment by yxw007** [comment]
> 你好，百度翻译的api，是否能够调用成功？我在填写相关信息后，返回了api错误码52003。
> 
> 具体信息：Translate fail ! error_code:52003, error_msg: UNAUTHORIZED USER
> 
> 查了下报错是用户未开通此项服务。但是我确实已经开通了，。将api填入到其他翻译插件，发现可以正常返回翻译内容。
> 
> ![image](https://github.com/user-attachments/assets/886f5644-d115-42c2-add5-8ae95be34ccb)
> 
> 查了相关教程，您看可能是您那边的调用代码有问题？https://blog.csdn.net/J_aSON_/article/details/114798090

看README_zh-CN.md文档FAQ，5003 是你配置没配对

**Comment by LY-zhang-yi-hao** [comment]
已经解决。报错信息：Translate fail ! error_code:52003, error_msg: UNAUTHORIZED USER 
刚开始开通的是通用文本翻译，报错出现了error_code:52003，需要开通领域翻译。
开通领域翻译后，可以正常使用了。
