### ISSUE TITLE
C函数翻译只能翻译出一行

### ISSUE THREAD

**Issue by zhe-shi-jia-de-yonghuming** [yxw007/vscode-translate-next#7]
![屏幕截图 2024-11-28 203341](https://github.com/user-attachments/assets/3f56ee15-05a8-4169-b38d-ff1decc00a74)

![image](https://github.com/user-attachments/assets/083079a9-e2c6-4f35-8a4d-22b4ffbc11d5)

https://github.com/microsoft/calculator
calculator-main\calculator-main\src\CalcManager\Header Files\History.h

1：找的微软的一个开源的小计算器项目中发现的，只翻译了一行内的代码

2：翻译了两遍，应该是先是一遍原文再是一遍翻译后吧

![image](https://github.com/user-attachments/assets/95ef326e-6191-4f20-9af6-da4f6ea1403c)
![image](https://github.com/user-attachments/assets/bbddd187-7ab1-4258-b1fc-9abcf76b7a11)

另外还有一个过于冷门的的vscode编程语言支持完全无法翻译调用的函数，只能跳转到定义位置对注释翻译，不过那应该是人家代码不靠谱的问题...那玩意都没人维护了，顺便问问（不回答也没事，毕竟这个问题挺过分的，而且我不一定听得懂），如果我要强行兼容这种情况的话，您有什么推荐的思路

**Comment by yxw007** [comment]
![image](https://github.com/user-attachments/assets/4df105c9-eba0-4e82-8f91-46face529ddc)
问题解决了，下个版本更新就可以了

**Comment by yxw007** [comment]
> > ![image](https://private-user-images.githubusercontent.com/9338717/390813597-4df105c9-eba0-4e82-8f91-46face529ddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDUwODUsIm5iZiI6MTczMjgwNDc4NSwicGF0aCI6Ii85MzM4NzE3LzM5MDgxMzU5Ny00ZGYxMDVjOS1lYmEwLTRlODItOGY5MS00NmZhY2U1MjlkZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMTQzOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJjNWNjNTNkZDE3Zjk5ODFiZjZlYmUzY2U1MDM3ODhiMzcxMzNmNWQ3YzIwM2VkODdhNTZmZDQ0OTNmMTI3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PmrAl5mRTmSkRyiy8OmWpROrCFESiy9_CDXGKB1w6Uo) 问题解决了，下个版本更新就可以了
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/22e363cd-ac67-466f-8d95-dbe6a559dfe6)
> 
> 我草大佬效率好高，但是这东西没换行啊

待会改点东西一起发布哈

**Comment by yxw007** [comment]
> > ![image](https://private-user-images.githubusercontent.com/9338717/390813597-4df105c9-eba0-4e82-8f91-46face529ddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDUwODUsIm5iZiI6MTczMjgwNDc4NSwicGF0aCI6Ii85MzM4NzE3LzM5MDgxMzU5Ny00ZGYxMDVjOS1lYmEwLTRlODItOGY5MS00NmZhY2U1MjlkZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMTQzOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJjNWNjNTNkZDE3Zjk5ODFiZjZlYmUzY2U1MDM3ODhiMzcxMzNmNWQ3YzIwM2VkODdhNTZmZDQ0OTNmMTI3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PmrAl5mRTmSkRyiy8OmWpROrCFESiy9_CDXGKB1w6Uo) 问题解决了，下个版本更新就可以了
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/22e363cd-ac67-466f-8d95-dbe6a559dfe6)
> 
> 我草大佬效率好高，但是这东西没换行啊

待会改点东西一起发布哈

**Comment by yxw007** [comment]
> > ![image](https://private-user-images.githubusercontent.com/9338717/390813597-4df105c9-eba0-4e82-8f91-46face529ddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDUwODUsIm5iZiI6MTczMjgwNDc4NSwicGF0aCI6Ii85MzM4NzE3LzM5MDgxMzU5Ny00ZGYxMDVjOS1lYmEwLTRlODItOGY5MS00NmZhY2U1MjlkZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMTQzOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJjNWNjNTNkZDE3Zjk5ODFiZjZlYmUzY2U1MDM3ODhiMzcxMzNmNWQ3YzIwM2VkODdhNTZmZDQ0OTNmMTI3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PmrAl5mRTmSkRyiy8OmWpROrCFESiy9_CDXGKB1w6Uo) 问题解决了，下个版本更新就可以了
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/22e363cd-ac67-466f-8d95-dbe6a559dfe6)
> 
> 我草大佬效率好高，但是这东西没换行啊

换行问题解决了，版本已更新
