### ISSUE TITLE
翻译出现错误

### ISSUE THREAD

**Issue by FUKUA2010** [yxw007/vscode-translate-next#9]
使用Google翻译，出现这个错误是啥情况？Translate fail ! Unexpected token '<', "<!DOCTYPE "... is not valid JSON
![image](https://github.com/user-attachments/assets/85854b39-d227-4aef-b4fe-57e3bab6f09b)

**Comment by yxw007** [comment]
> 使用Google翻译，出现这个错误是啥情况？Translate fail ! Unexpected token '<', "<!DOCTYPE "... is not valid JSON ![image](https://private-user-images.githubusercontent.com/35751633/391867106-85854b39-d227-4aef-b4fe-57e3bab6f09b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjA2OTgsIm5iZiI6MTczMzIyMDM5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE4NjcxMDYtODU4NTRiMzktZDIyNy00YWVmLWI0ZmUtNTdlM2JhYjZmMDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEwMDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTAxNGU5YjY0ZGI0OWE0OTdlN2RiZWY5MTU5YmNjODBjOGQ3NTJjNDFkMWNlMDhjZTc2ODA3YzJmYjQ5YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ezBZcRBF0Ska7URVdrHElT3d4t9O1G0FHMfGB7IA8ok)

具体怎么复现问题啊？

**Comment by FUKUA2010** [comment]
> > 使用Google翻译，出现这个错误是啥情况？Translate fail ! Unexpected token '<', "<!DOCTYPE "... is not valid JSON <img alt="image" width="57.48749923706055" height="21" src="https://private-user-images.githubusercontent.com/35751633/391867106-85854b39-d227-4aef-b4fe-57e3bab6f09b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjA2OTgsIm5iZiI6MTczMzIyMDM5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE4NjcxMDYtODU4NTRiMzktZDIyNy00YWVmLWI0ZmUtNTdlM2JhYjZmMDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEwMDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTAxNGU5YjY0ZGI0OWE0OTdlN2RiZWY5MTU5YmNjODBjOGQ3NTJjNDFkMWNlMDhjZTc2ODA3YzJmYjQ5YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ezBZcRBF0Ska7URVdrHElT3d4t9O1G0FHMfGB7IA8ok">
> 
> 具体怎么复现问题啊？
随意点击任意地方的英文都会出现这个错误，完全用不了
![PixPin_2024-12-03_19-01-43](https://github.com/user-attachments/assets/f63e9521-75ae-4037-ab7e-67a697698a0c)

**Comment by yxw007** [comment]
> > > 使用Google翻译，出现这个错误是啥情况？Translate fail ! Unexpected token '<', "<!DOCTYPE "... is not valid JSON <img alt="image" width="57.48749923706055" height="21" src="https://private-user-images.githubusercontent.com/35751633/391867106-85854b39-d227-4aef-b4fe-57e3bab6f09b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjA2OTgsIm5iZiI6MTczMzIyMDM5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE4NjcxMDYtODU4NTRiMzktZDIyNy00YWVmLWI0ZmUtNTdlM2JhYjZmMDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEwMDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTAxNGU5YjY0ZGI0OWE0OTdlN2RiZWY5MTU5YmNjODBjOGQ3NTJjNDFkMWNlMDhjZTc2ODA3YzJmYjQ5YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ezBZcRBF0Ska7URVdrHElT3d4t9O1G0FHMfGB7IA8ok">
> 
> > 
> 
> > 具体怎么复现问题啊？
> 
> 随意点击任意地方的英文都会出现这个错误，完全用不了
> 
> ![PixPin_2024-12-03_19-01-43](https://github.com/user-attachments/assets/f63e9521-75ae-4037-ab7e-67a697698a0c)
> 
> 

你没有翻墙吧

**Comment by FUKUA2010** [comment]
> > > > 使用Google翻译，出现这个错误是啥情况？Translate fail ! Unexpected token '<', "
> > 
> > 
> > > 
> > 
> > 
> > > 具体怎么复现问题啊？
> > 
> > 
> > 随意点击任意地方的英文都会出现这个错误，完全用不了
> > ![PixPin_2024-12-03_19-01-43](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> >       
> >         [
> >           
> >         
> >             ![PixPin_2024-12-03_19-01-43](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> >           ](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> 
> 你没有翻墙吧，刚刚我测试了一下，挺正常呀。

应该是网络的问题，代理我也设置好了，谷歌ping不通。clash开启tun模式，能ping通，但是还是用不了。申请了百度api，可以用，很奇怪，试了好几种方法都不行，vscode设置代理，命令行，环境变量都不行。
![image](https://github.com/user-attachments/assets/f0ee936f-f534-4c0d-bbbd-a6687a37d51e)

**Comment by yxw007** [comment]
> > > > > 使用Google翻译，出现这个错误是啥情况？Translate fail ! Unexpected token '<', "
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 具体怎么复现问题啊？
> > > 
> > > 
> > > 随意点击任意地方的英文都会出现这个错误，完全用不了
> > > ![PixPin_2024-12-03_19-01-43](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> > >       
> > >         [
> > >           
> > >             ![PixPin_2024-12-03_19-01-43](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> > >           
> > >         ](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >     
> > >         ![PixPin_2024-12-03_19-01-43](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> > >       ](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://private-user-images.githubusercontent.com/35751633/391936827-f63e9521-75ae-4037-ab7e-67a697698a0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODk1OTgsIm5iZiI6MTczMzI4OTI5OCwicGF0aCI6Ii8zNTc1MTYzMy8zOTE5MzY4MjctZjYzZTk1MjEtNzVhZS00MDM3LWFiN2UtNjdhNjk3Njk4YTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzQwNDM1MzgxOWY1MTQzZWU1MzMyZGFmYTUyYmNiZTBkMGVkZTRiYTBiYmIzODNjNjQ3MTk3N2ZhNWMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZIRwqSlIKqRq0IlO5_fRv4rVahiFtpnjglJflx64BA)
> > > ```
> > 
> > 
> > 你没有翻墙吧，刚刚我测试了一下，挺正常呀。
> 
> 应该是网络的问题，代理我也设置好了，谷歌ping不通。clash开启tun模式，能ping通，但是还是用不了。申请了百度api，可以用，很奇怪，试了好几种方法都不行，vscode设置代理，命令行，环境变量都不行。 ![image](https://private-user-images.githubusercontent.com/35751633/392235116-f0ee936f-f534-4c0d-bbbd-a6687a37d51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDI1NTQsIm5iZiI6MTczMzMwMjI1NCwicGF0aCI6Ii8zNTc1MTYzMy8zOTIyMzUxMTYtZjBlZTkzNmYtZjUzNC00YzBkLWJiYmQtYTY2ODdhMzdkNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA4NTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYmUyN2JkMGM2ZDcwMWViYTI0NDdjNmZhMmJlZjdmMmMzMTM5ZThhZmE4OGJmZjk0ODNjYmNjY2I1ZWYxMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TINKfqaRskSUQZPbn3FsrxLfYngKbPow9G4FJ5L-kv4)

google 引擎，底层调用的接口是：
https://translate.googleapis.com/translate_a/single?client=gtx&sl=zh-CN&tl=en&dt=t&q=你好
![1](https://github.com/user-attachments/assets/cf2cbc1b-f201-4764-ad59-757727945959)

如果你环境能正常调用，那么翻译就没有问题，如果无法正常调用接口，那就用baidu吧。
